# Generated by Django 3.0.8 on 2020-07-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='is_blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
