# Generated by Django 3.0.3 on 2020-02-10 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=128, unique=True)),
                ('avatar_url', models.TextField(null=True)),
                ('password_hash', models.CharField(max_length=512)),
                ('secret_key', models.CharField(db_index=True, default='', max_length=108)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
