# Generated by Django 3.0.3 on 2020-02-20 18:19

import _common.utils
import _common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.CharField(db_index=True, default=_common.utils.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, editable=False, max_length=128, unique=True, validators=[_common.validators.UsernameValidator])),
                ('email', models.EmailField(db_index=True, max_length=128, unique=True)),
                ('avatar_uuid', models.CharField(max_length=36, null=True)),
                ('password_hash', models.CharField(max_length=512)),
                ('secret_key', models.CharField(db_index=True, default='', max_length=108)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db': 'default',
            },
        ),
    ]
