# Generated by Django 3.0.8 on 2020-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='agent',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='http_accept',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='path_info',
            field=models.TextField(default=''),
        ),
    ]
